### ISSUE TITLE
Вопрос по SAV файлам (not issue)

### ISSUE THREAD

**Issue by y-salnikov** [nzeemin/ukncbtl-utils#1]
Здравствуйте.
Я разрабатываю аппаратный эмулятор контроллера дисковода для МС0511, который использует образы дисков на SD-карте. В принципе, все работает, можно заггрузиться, читать и писать файлы в RT-11 на реальной машине.  Сейчас нужно написать программу под RT-11,  которая будет взаимодействовать с моим драйвером и "мапить" образы дисков к виртуальным дисководам. Весь бэкенд готов, но не проверялся. Проблема в том, что я совершенно не знаком с RT-11 и не знаю как сформировать SAV файл и как распарсить аргументы командной строки. Ассемблеру макро-11 я тоже не обучен, так как привык программировать прямо в кодах, даже инструмент свой написал : https://github.com/y-salnikov/not-yet-assembler. Собственно вопрос, как создать SAV файл с имеющимся кодом и как распарсить аргументы программы под RT-11?

**Comment by nzeemin** [comment]
Советую вам обратиться на форум http://zx-pk.ru/forumdisplay.php?f=66 -- здесь довольно активное сообщество тех кто хорошо знает и понимает работу RT-11. Я в этом плане скорее новичок.
Ассемблер MACRO11 довольно простой, на него есть подробные доки.
Советую также использовать RT-11 из командной строки: http://zx-pk.ru/showthread.php?t=24755 -- это сильно упрощает работу. Вы можете посмотреть мой проект unkc-loderunner как пример использования MACRO + LINK для компиляции.
Для разобора командной строки для MACRO есть стандартные макросы в стандартной макро-библиотеке, такие как .CSIGEN/.CSISPC, "Command String Interpreter".
