### ISSUE TITLE
rt11dsk - ошибки подсчёта файлов и блоков 

### ISSUE THREAD

**Issue by Radon17** [nzeemin/ukncbtl-utils#11]
Образ ЖД от ДВК. 

Реальная машина (физический ЖД)
![изображение](https://user-images.githubusercontent.com/48731744/138449976-8bba3ba3-e73f-4e97-bb51-7b57db8a8649.png)
Эмулятор ДВК (образ)
![изображение](https://user-images.githubusercontent.com/48731744/138450027-b4ca4e51-8da9-4031-8461-204115af78a5.png)
RT11DSK (тот же образ)
![изображение](https://user-images.githubusercontent.com/48731744/138450074-598f33af-0aa7-460d-8084-e2680891981b.png)

**Comment by nzeemin** [comment]
@Radon17 ошибка налицо, а скажите, этот образ диска где-то можно скачать?

**Comment by Radon17** [comment]
> ошибка налицо, а скажите, этот образ диска где-то можно скачать?

@nzeemin Образ я снимал пару дней назад со своего диска (машина раньше стояла в школе). 
Выложил [сюда](https://dropmefiles.com/L1b72). Интересных файлов там особо нет, машину больше использовали как печатную машинку аж до 99-го года. Кстати у меня в эмуляторе ДВК образ не загружается, хотя диск системный и на реале грузится. Просматривал его загрузившись с MY:. Но это уже вопросы совершенно не к вам.

**Comment by nzeemin** [comment]
Выяснил, так происходит из-за двух записей, помеченых как TENTATIVE, команда DIR показывает их как UNUSED:
```
Filename  Blocks  Date        Start    Bytes
1     .OBJ    44  07-Nov-1989 15522    22528
L1    .TXT    45  05-Feb-1999 17714    23040
```

**Comment by nzeemin** [comment]
Исправил коммитом c43dd512b4ecba6cd9b217b0f1a7a34824e3c71a
